version: '3'
services:
  stayrtr:
    build:
      dockerfile: Dockerfile.stayrtr
      context: .
    command:
      - -cache
      - rpki.json
      - -slurm
      - slurm.json
      - -verify=false
    volumes:
      - ./cmd/stayrtr/test.rpki.json:/rpki.json
      - ./cmd/stayrtr/test.slurm.json:/slurm.json
  rtrdump:
    build:
      dockerfile: Dockerfile.rtrdump
      context: .
    command:
      - -connect
      - stayrtr:8282
      - -file
      - ""
    depends_on:
      - stayrtr
