name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Set up go version from go.mod
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Test & Vet
      run: make test vet

    - name: Build
      run: |
        GOOS=linux make build-stayrtr
        GOOS=linux GOARCH=arm64 make build-stayrtr
        GOOS=darwin make build-stayrtr
        GOOS=windows EXTENSION=.exe make build-stayrtr
        GOOS=linux make build-rtrdump
        GOOS=linux GOARCH=arm64 make build-rtrdump
        GOOS=darwin make build-rtrdump
        GOOS=windows EXTENSION=.exe make build-rtrdump
        GOOS=linux make build-rtrmon
        GOOS=linux GOARCH=arm64 make build-rtrmon
        GOOS=darwin make build-rtrmon
        GOOS=windows EXTENSION=.exe make build-rtrmon

    - name: Install fpm
      run: |
        sudo apt-get update
        sudo apt-get install -y rpm ruby ruby-dev
        sudo gem install fpm

    - name: Package
      run: |
        make package-deb-stayrtr package-rpm-stayrtr
        GOARCH=arm64 make package-deb-stayrtr package-rpm-stayrtr

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/*
        retention-days: 14
